import Foundation

/// Draft → markdown renderer for the export path. Mirrors the
/// sheet's reading order: header metadata, one section per item
/// (scores, comment, evidence), conflicts called out inline.
/// Inferred scores are explicitly marked — they are suggestions,
/// not sheet entries.
public enum EvalFormMarkdown {
    public static func render(
        draft: EvalFormDraft,
        template: EvalFormTemplate,
        sessionTitle: String
    ) -> String {
        var lines: [String] = []
        lines.append("# \(template.name)")
        if !sessionTitle.isEmpty {
            lines.append("Session: \(sessionTitle)")
        }
        lines.append("")

        if !draft.metadata.isEmpty {
            lines.append("## ヘッダ")
            for field in template.metadataFields {
                if let value = draft.metadata[field] {
                    lines.append("- \(field): \(value)")
                }
            }
            lines.append("")
        }

        lines.append("## 評価項目")
        for item in template.items {
            let result = draft.items.first { $0.itemID == item.id }
            lines.append("### \(item.number). \(item.titleJa)")
            let score: String
            if let stated = result?.strengthScore {
                score = formatted(stated)
            } else if let inferred = result?.strengthScoreInferred {
                score = "（推定 \(formatted(inferred)) — 要確認）"
            } else {
                score = "—"
            }
            lines.append("- 評点（基準比）: \(score)")
            lines.append("- 好き嫌い (1–9): \(result?.likeDislike.map(String.init) ?? "—")")
            let roads = draft.roadsForItem(item.id)
            if !roads.isEmpty {
                lines.append("- 走行路: \(roads.joined(separator: ", "))")
            }
            if let comment = result?.comment {
                lines.append("- コメント: \(comment)")
            }
            if let evidence = result?.evidenceRows, !evidence.isEmpty {
                lines.append("- 根拠発話: \(evidenceText(evidence, roadByRow: draft.roadByRow))")
            }
            for conflict in result?.conflicts ?? [] {
                lines.append("- ⚠ \(conflict)")
            }
            lines.append("")
        }

        if let supplementary = draft.supplementaryComment {
            lines.append("## 補足コメント")
            lines.append(supplementary)
            if let evidence = draft.supplementaryEvidenceRows, !evidence.isEmpty {
                lines.append("")
                lines.append("根拠発話: \(evidenceText(evidence, roadByRow: draft.roadByRow))")
            }
            lines.append("")
        }

        // The to-fill list: everything the extraction did NOT
        // detect, so the sheet's remaining manual work is explicit.
        let undetected = EvalFormCoverage.undetected(
            draft: draft,
            template: template
        )
        if !undetected.isEmpty {
            lines.append("## 未検出（要手動記入）")
            if !undetected.missingHeaderFields.isEmpty {
                lines.append("- ヘッダ: \(undetected.missingHeaderFields.joined(separator: ", "))")
            }
            for gaps in undetected.items {
                guard let item = template.items.first(where: { $0.id == gaps.itemID })
                else { continue }
                lines.append("- \(item.number). \(item.titleJa): \(EvalFormCoverage.gapPhrase(gaps))")
            }
            lines.append("")
        }

        lines.append("---")
        lines.append("Generated by Xephon VehiclePerformanceMetricsA_1_Straight plugin — stated-only scores; inferred values are marked and need reviewer confirmation.")
        return lines.joined(separator: "\n")
    }

    private static func formatted(_ value: Double) -> String {
        let sign = value > 0 ? "+" : ""
        return "\(sign)\(String(format: "%g", value))"
    }

    /// Evidence rows, grouped by road provenance when the draft
    /// carries it: "D路 [16] [36] ・ 段差路 [58] ・ — [73]".
    static func evidenceText(
        _ rows: [Int],
        roadByRow: [Int: String]?
    ) -> String {
        guard let roadByRow, !roadByRow.isEmpty else {
            return rows.map { "[\($0)]" }.joined(separator: " ")
        }
        var order: [String] = []
        var byRoad: [String: [Int]] = [:]
        for row in rows {
            let road = roadByRow[row] ?? "—"
            if byRoad[road] == nil { order.append(road) }
            byRoad[road, default: []].append(row)
        }
        return order.map { road in
            let chips = (byRoad[road] ?? []).map { "[\($0)]" }.joined(separator: " ")
            return "\(road) \(chips)"
        }.joined(separator: " ・ ")
    }
}
