import Foundation

/// Draft → markdown renderer for the export path. Mirrors the
/// sheet's reading order: header metadata, one section per item
/// (scores, comment, evidence), conflicts called out inline.
/// Inferred scores are explicitly marked — they are suggestions,
/// not sheet entries.
public enum EvalFormMarkdown {
    public static func render(
        draft: EvalFormDraft,
        template: EvalFormTemplate,
        sessionTitle: String
    ) -> String {
        var lines: [String] = []
        lines.append("# \(template.name)")
        if !sessionTitle.isEmpty {
            lines.append("Session: \(sessionTitle)")
        }
        lines.append("")

        if !draft.metadata.isEmpty {
            lines.append("## ヘッダ")
            for field in template.metadataFields {
                if let value = draft.metadata[field] {
                    lines.append("- \(field): \(value)")
                }
            }
            lines.append("")
        }

        lines.append("## 評価項目")
        for item in template.items {
            let result = draft.items.first { $0.itemID == item.id }
            lines.append("### \(item.number). \(item.titleJa)")
            let score: String
            if let stated = result?.strengthScore {
                score = formatted(stated)
            } else if let inferred = result?.strengthScoreInferred {
                score = "（推定 \(formatted(inferred)) — 要確認）"
            } else {
                score = "—"
            }
            lines.append("- 評点（基準比）: \(score)")
            lines.append("- 好き嫌い (1–9): \(result?.likeDislike.map(String.init) ?? "—")")
            if let comment = result?.comment {
                lines.append("- コメント: \(comment)")
            }
            if let evidence = result?.evidenceRows, !evidence.isEmpty {
                lines.append("- 根拠発話: \(evidence.map { "[\($0)]" }.joined(separator: " "))")
            }
            for conflict in result?.conflicts ?? [] {
                lines.append("- ⚠ \(conflict)")
            }
            lines.append("")
        }

        if let supplementary = draft.supplementaryComment {
            lines.append("## 補足コメント")
            lines.append(supplementary)
            lines.append("")
        }

        lines.append("---")
        lines.append("Generated by Xephon EvalFormPlugin — stated-only scores; inferred values are marked and need reviewer confirmation.")
        return lines.joined(separator: "\n")
    }

    private static func formatted(_ value: Double) -> String {
        let sign = value > 0 ? "+" : ""
        return "\(sign)\(String(format: "%g", value))"
    }
}
